### ISSUE TITLE
Wrong index.publisher field being generated for some records

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1196]
The suggestion with id `399405c701a14278b54c94529c7144e2` in live has the following field in its `index` section:

```json
"publisher": "[u'SN Education Society']"
```

That's weird, and it makes searches that have specified "search only in the publisher field" fail.

Rikard has reported it for some journals as well, although a short while later, when I viewed the search link, the journal was showing up correctly. I don't know whether this application will also fix itself, but it shouldn't be broken in the first place, obviously. It seems like the result of a deterministic problem, like it would either work correctly or not.

Here's the search link by Rikard: http://bit.ly/2jJzFHN . At the time of writing this shows "no results". Change the field-to-search-in to "search all" instead of "Publisher" and you will see the records appear. That's probably because "Publisher" translates to "index.publisher.exact".

I don't know how high priority this is, but I suppose not being able to discover records in the obvious ways is not something we want to keep around for too long.

**Comment by emanuil-tolev** [comment]
This could be caused by earlier code that is now fixed in production, by the way - something to keep in mind while trying to reproduce locally. So locally, if you put `[u'SN Education Society']` into index.publisher of an application, and then .save() it, that might well fix it. If so the obvious overall fix would be a simple migration.

**Comment by richard-jones** [comment]
I've looked at suggestion 399405c701a14278b54c94529c7144e2 and it looks fine now.

Inspecting the code, it looks like the struct is wrong, though.  It says that publisher is a single value unicode field, but it's actually a list of unicodes.

So, no risk of data loss here, but I'll straighten out the struct and provide a hotfix shortly.

**Comment by ClaraDOAJ** [comment]
Looks like it is fixed! Many thanks

**Comment by ClaraDOAJ** [comment]
We are still seeing the problem in the Admin - Applications
![image](https://cloud.githubusercontent.com/assets/22593616/23204381/b194ae52-f8e6-11e6-8267-037f8394ab70.png)

**Comment by richard-jones** [comment]
Apologies, this is my fault, I didn't update the application model definition to store the index.publisher correctly there - only for the journals themselves.

I have submitted a PR for this: #1230

**Comment by richard-jones** [comment]
Fixed on live
